# Generated by Django 2.2.6 on 2019-10-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='isdelete',
            new_name='isDelete',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='method',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='isdelete',
            new_name='isDelete',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='read_count',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='commentcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='readcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='peopleinfo',
        ),
    ]
