# Generated by Django 2.2.6 on 2019-10-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20191011_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='Book/')),
            ],
            options={
                'db_table': 'pictureinfo',
            },
        ),
    ]
